{
 "title": "Spring Boot HikariCP / JDBC",
 "description": "HikariCP & JDBC Dashboard (Micrometer.io)",
 "tags": [
  "prometheus",
  "hikaricp",
  "micrometer",
  "spring boot",
  "jdbc"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(jdbc_connections_min{application=\"$application\"}, region)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jdbc_connections_min{application=\"$application\", region=~\"$region\"}, instance)"
   },
   {
    "name": "jdbc_connection_name",
    "label": "JDBC Connection Name",
    "query": "label_values(jdbc_connections_min{application=\"$application\", region=~\"$region\", instance=~\"$instance\"}, name)"
   },
   {
    "name": "hikaricp_pool_name",
    "label": "Hikari  Pool Name",
    "query": "label_values(hikaricp_connections_min{application=\"$application\", region=~\"$region\", instance=~\"$instance\"}, pool)"
   }
  ]
 },
 "panels": [
  { "title": "Application and APIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application Status",
   "type": "stat",
   "description": "Shows whether the Spring Boot Application is Up or Down",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"spring-actuator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API request Rate",
   "type": "timeseries",
   "description": "Calculates the rate of request to the respective API endpoint over 10 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/api/v1/users/getUsers\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Request Count of endpoint- \"/api/v1/users/getUsers\"",
   "type": "stat",
   "description": "Total successful request count of endpoint- \"/api/v1/users/getUsers\"",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/api/v1/users/getUsers\",status=\"200\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "JDBC Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jdbc_connections_min{application=\"$application\", region=~\"$region\", instance=~\"$instance\", name=~\"$jdbc_connection_name\"}"
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jdbc_connections_active{application=\"$application\", region=~\"$region\", instance=~\"$instance\", name=~\"$jdbc_connection_name\"}"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jdbc_connections_max{application=\"$application\", region=~\"$region\", instance=~\"$instance\", name=~\"$jdbc_connection_name\"}"
    }
   ]
  },
  {
   "title": "Hikari Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}",
     "legendFormat": "Active connections"
    },
    {
     "expr": "hikaricp_connections_idle{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}",
     "legendFormat": "Idle connections"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}",
     "legendFormat": "Pending threads"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_max{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}"
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_min{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}"
    }
   ]
  },
  {
   "title": "Total Timeout",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}"
    }
   ]
  },
  {
   "title": "Connections Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "irate(hikaricp_connections_usage_seconds_sum{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m]) / irate(hikaricp_connections_usage_seconds_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m])",
     "legendFormat": "Usage time"
    },
    {
     "expr": "irate(hikaricp_connections_creation_seconds_sum{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m]) / irate(hikaricp_connections_creation_seconds_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m])",
     "legendFormat": "Creation time"
    },
    {
     "expr": "irate(hikaricp_connections_acquire_seconds_sum{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m]) / irate(hikaricp_connections_acquire_seconds_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m])",
     "legendFormat": "Acquire time"
    }
   ]
  }
 ]
}